# Generated by Django 4.2.5 on 2023-09-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a',
        ),
    ]
