# Generated by Django 4.2.5 on 2023-12-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs_level',
            new_name='jobslevel',
        ),
    ]
