# Generated by Django 4.2.5 on 2023-12-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_jobs_level_jobslevel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='tpo',
        ),
    ]
